name: Rust

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          default: true
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
      - run: cargo rustc --locked -- -D warnings
      - run: cargo clippy --locked -- -D warnings
      - run: cargo test
